services:

  neo4j:
    image: neo4j:5.21
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-brahmsian}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
